---
# Regex to validate foo in <foo>. Defaults to /\A[a-z0-9\-\:]+\z/.
# partial_tag_name_pattern:

# Regex to validate bar in <foo bar=1>. Defaults to /\A[a-zA-Z0-9\-\:]+\z/.
# partial_attribute_name_pattern:

# When true, <foo bar='1'> is valid syntax. Defaults to true.
# allow_single_quoted_attributes:

# When true, <foo bar=1> is valid syntax. Defaults to false.
# allow_unquoted_attributes:

# List of methods that return javascript-safe strings. This list is used by SafeErbTester when determining whether ruby
# interpolation is safe for a given attribute. Defaults to ['to_json'].
# javascript_safe_methods:

# Same as javascript_safe_methods, but for lodash templates. Defaults to [/\AJSON\.stringify\(/].
# lodash_safe_javascript_expression:

# List of all attribute names that contain javascript code. This list is used by SafeErbTester when determining whether
# or not a given attribute value will be eval'ed as javascript. Defaults to [/\Aon/i] (matches onclick for example).
# javascript_attribute_names:

# This is called when determining whether to apply runtime checks on a .erb template. When this Proc returns false, no
# safety checks are applied and parsing is done using the default Rails erubi engine. For example, to exclude erb
# templates provided by libraries, use: Proc.new { |filename| !filename.start_with?(Rails.root.to_s) }. Defaults to nil
# (all html.erb templates are parsed).
# template_exclusion_filter:
