default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: canaco-b2b_development

test:
  <<: *default
  database: canaco-b2b_test

production:
  <<: *default
  database: canaco-b2b_production
  url: <%= ENV['DATABASE_URL'] %>
